# Generated by Django 3.1.14 on 2022-07-24 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0002_auto_20220724_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abouts',
            options={},
        ),
    ]
