# Generated by Django 3.2.13 on 2022-07-14 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_frames'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Frames',
        ),
    ]
