# Generated by Django 3.1.14 on 2022-07-18 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_frames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='frame',
        ),
    ]
