# Generated by Django 3.1.14 on 2022-07-19 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imageFramed',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imageWall',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('imageFramed', models.ImageField(blank=True, null=True, upload_to='')),
                ('imageWall', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
    ]
